#!/bin/bash
# Written by Msprg
# updated to quigg rc sockets by sdrabent

socket_A()
{
if [ "$1" == 0 ]
then
  echo "socket A off"
  ./codesend 9364000 4 374
fi

if [ "$1" == 1 ]
then
  echo "socket A on"
  ./codesend 8766528 4 374
fi
}

socket_B()
{
if [ "$1" == 0 ]
then
  echo "socket B off"
  ./codesend 8930580 4 374
fi

if [ "$1" == 1 ]
then
  echo "socket B on"
  ./codesend 8584756 4 374
fi
}

socket_C()
{
if [ "$1" == 0 ]
then
  echo "socket C off"
  ./codesend 9364012 4 374
fi

if [ "$1" == 1 ]
then
  echo "socket C on"
  ./codesend 8766540 4 374
fi
}

socket_D()
{
if [ "$1" == 0 ]
then
  echo "socket D off"
  ./codesend 8605810 4 374
fi

if [ "$1" == 1 ]
then
  echo "socket D on"
  ./codesend 8930578 4 374
fi
}

socket_ALL()
{
if [ "$1" == 0 ]
then
  echo "ALL sockets off"
  ./codesend 2580754 4 355
fi

if [ "$1" == 1 ]
then
  echo "ALL sockets on"
  ./codesend 2681010 4 355
fi
}

show_help()
{
echo "Usage: socket (A|B|C|D|ALL) (1|0)"
}


if [ "$1" == A ]
then
  socket_A $2
elif [ "$1" == B ]
then
  socket_B $2
elif [ "$1" == C ]
then
  socket_C $2
elif [ "$1" == D ]
then
  socket_D $2
elif [ "$1" == ALL ]
then
  socket_ALL $2
else
  show_help
fi

